export const FETCHED_DATA_RECEIVED = 'FETCHED_DATA_RECEIVED'
export const INCREMENT_PROGRESS_BAR = 'INCREMENT_PROGRESS_BAR'
export const RESET_PROGRESS_BAR = 'RESET_PROGRESS_BAR'
export const IS_FETCHING = 'IS_FETCHING'
